### ISSUE TITLE
Expose more details from Geonames.org. Example: Currency and Languages

### ISSUE THREAD

**Issue by Korayem** [RobThree/NISOCountries#1]
One of the beautiful values that is used a lot is getting _Currency_ and _Default Language**(s)**_ `http://download.geonames.org/export/dump/countryInfo.txt`

The following are frequently used:
- CurrencyCode
- CurrencyName
- Phone
- Language**(s)**
- Postal Code Regex

Would be great to get those properties on `GeoNameCountry` class

**Comment by RobThree** [comment]
You could use [NGeoNames](https://github.com/RobThree/NGeoNames) for that. I don't think those properties belong in a library that is designed only to deal with (ISO) countrycodes. The NGeoNames project exposes [all of those properties (and more)](https://github.com/RobThree/NGeoNames/blob/master/NGeoNames/Entities/CountryInfo.cs).

**Comment by Korayem** [comment]
Ok cool! that sounds more appropriate indeed. Thanks!
